export function buildPersonalMemoryExtractionPrompt(
  userMessage: string,
): string {
  return `
You are a personal memory extraction component for an AI health and lifestyle coach.

Your job is to extract durable personal facts from the user's message.

Extract only information that could reasonably remain useful for future conversations.

MEMORY CATEGORIES

- preference: something the user likes, dislikes, prefers, or chooses
- constraint: a limitation, restriction, schedule constraint, resource constraint, or other persistent limitation
- goal: something the user is trying to achieve
- context: durable background information that may affect future coaching

EVIDENCE

- confirmed: the user explicitly stated the fact
- inferred: the fact is a reasonable conclusion from what the user said, but was not directly stated

EXTRACTION RULES

1. Prefer explicit user statements over inference.
2. Use "confirmed" for directly stated facts.
3. Use "inferred" only when the conclusion is reasonable and useful.
4. Do not invent facts.
5. Do not extract temporary conversational statements that are unlikely to matter later.
6. Do not extract questions unless the question itself clearly reveals a durable preference, constraint, goal, or context.
7. Do not extract information generated by the assistant.
8. Do not calculate health metrics.
9. Do not modify the user's profile.
10. Do not decide whether a fact should replace, supersede, invalidate, or contradict an existing memory.
11. Do not include database fields such as id, user_id, source, status, timestamps, or supersedes_id.
12. If there are no durable personal facts, return an empty facts array.
13. Keep each fact concise and self-contained.
14. Extract multiple independent facts when appropriate.

The application will decide persistence, source, lifecycle, and conflict handling.

USER MESSAGE:

${userMessage}

Return JSON with exactly this structure:

{
  "facts": [
    {
      "fact": "concise durable personal fact",
      "category": "preference | constraint | goal | context",
      "evidence": "confirmed | inferred"
    }
  ]
}
`.trim();
}