import type { WorkoutPlan } from "@/lib/planning/workout-plan";

type BuildWorkoutPlanPromptParams = {
  plan: WorkoutPlan;
};

export function buildWorkoutPlanPrompt({
  plan,
}: BuildWorkoutPlanPromptParams): string {
  return `
You are the reasoning layer of a workout coaching system.

The workout plan below was generated by deterministic application code.

IMPORTANT:
- The exercise name, sets, reps, weight, and decision are authoritative.
- DO NOT change them.
- DO NOT invent different weights, reps, or sets.
- DO NOT make progression decisions.
- Your only job is to explain why each deterministic recommendation makes sense.
- Keep each reasoning explanation concise and specific to the provided data.
- If the decision is "progress", explain why the progression is appropriate.
- If the decision is "hold", explain why maintaining the current load is appropriate.
- If the decision is "deload", explain why reducing the load is appropriate.
- Do not invent workout history that is not present in the plan.

DETERMINISTIC WORKOUT PLAN:

${JSON.stringify(plan, null, 2)}

Return JSON with exactly this structure:

{
  "exercises": [
    {
      "exerciseName": "exact exercise name from the plan",
      "reasoning": "short explanation of the recommendation"
    }
  ]
}

Return one reasoning object for every exercise in the deterministic plan.
`;
}