import { describe, expect, it } from "vitest";
import { buildWorkoutPlanPrompt } from "@/lib/ai/coach/workout-plan-prompt";

describe("buildWorkoutPlanPrompt", () => {
  it("includes the deterministic workout plan", () => {
    const plan = {
      exercises: [
        {
          exerciseName: "Bench Press",
          sets: 3,
          reps: 8,
          weight: 82.5,
          decision: "progress" as const,
          reasonCode: "progressed" as const,
          daysSinceLastTrained: 2,
        },
      ],
    };

    const prompt = buildWorkoutPlanPrompt({ plan });

    expect(prompt).toContain("Bench Press");
    expect(prompt).toContain('"sets": 3');
    expect(prompt).toContain('"reps": 8');
    expect(prompt).toContain('"weight": 82.5');
    expect(prompt).toContain('"decision": "progress"');
    expect(prompt).toContain('"reasonCode": "progressed"');
    expect(prompt).toContain('"daysSinceLastTrained": 2');
  });

  it("tells the AI not to change deterministic recommendations", () => {
    const prompt = buildWorkoutPlanPrompt({
      plan: {
        exercises: [],
      },
    });

    expect(prompt).toContain(
      "The exercise name, sets, reps, weight, and decision are authoritative."
    );

    expect(prompt).toContain(
      "DO NOT change them."
    );

    expect(prompt).toContain(
      "DO NOT invent different weights, reps, or sets."
    );

    expect(prompt).toContain(
      "DO NOT make progression decisions."
    );
  });

  it("assigns decision-making to deterministic application code", () => {
    const prompt = buildWorkoutPlanPrompt({
      plan: {
        exercises: [],
      },
    });

    expect(prompt).toContain(
      "The workout plan below was generated by deterministic application code."
    );

    expect(prompt).toContain(
      "Your only job is to explain why each deterministic recommendation makes sense."
    );
  });

  it("instructs the AI to explain each supported decision", () => {
    const prompt = buildWorkoutPlanPrompt({
      plan: {
        exercises: [],
      },
    });

    expect(prompt).toContain(
      'If the decision is "progress", explain why the progression is appropriate.'
    );

    expect(prompt).toContain(
      'If the decision is "hold", explain why maintaining the current load is appropriate.'
    );

    expect(prompt).toContain(
      'If the decision is "deload", explain why reducing the load is appropriate.'
    );
  });

  it("requires reasoning for every exercise", () => {
    const prompt = buildWorkoutPlanPrompt({
      plan: {
        exercises: [
          {
            exerciseName: "Squat",
            sets: 3,
            reps: 6,
            weight: 100,
            decision: "hold",
            reasonCode: "maintain_after_decline",
            daysSinceLastTrained: 3,
          },
        ],
      },
    });

    expect(prompt).toContain(
      "Return one reasoning object for every exercise in the deterministic plan."
    );

    expect(prompt).toContain(
      '"exerciseName": "exact exercise name from the plan"'
    );

    expect(prompt).toContain(
      '"reasoning": "short explanation of the recommendation"'
    );
  });

  it("prevents the AI from inventing workout history", () => {
    const prompt = buildWorkoutPlanPrompt({
      plan: {
        exercises: [],
      },
    });

    expect(prompt).toContain(
      "Do not invent workout history that is not present in the plan."
    );
  });
});